[package]
name = "lnp-core"
version = "0.4.0-alpha.1"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "LNP Core Library: rust implementation of modular lightning channels architecture"
repository = "https://github.com/LNP-BP/lnp-core"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
edition = "2018"
exclude = [".github", "contrib", "lightning_encoding", "lnp2p"]

[lib]
name = "lnp"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
amplify = { version = "3", features = ["stringly_conversions"] }
amplify_derive = "2.4.3"
lnpbp = { git = "https://github.com/LNP-BP/rust-lnpbp" }
rgb-core = { git = "https://github.com/rgb-org/rgb-core", optional = true }
strict_encoding = "1"
lightning_encoding = { git = "https://github.com/LNP-BP/lnp-core", path = "lightning_encoding" }
descriptor-wallet = { git = "https://github.com/LNP-BP/descriptor-wallet", features = ["keygen"] }
bitcoin = { version = "0.26", features = ["rand"] }
internet2 = { git = "https://github.com/internet2-org/rust-internet2" }
serde_crate = { package = "serde", version = "1.0", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }
lazy_static = "1.4"

[features]
default = []
all = ["rgb", "serde"]
rgb = ["rgb-core"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/use-serde"]

[workspace]
members = [".", "lightning_encoding", "lightning_encoding/derive"] #, "lnp2p", ]
default-members = [".", "lightning_encoding", "lightning_encoding/derive"] #, "lnp2p", ]
exclude = ["dep_test"]
